"""create initial schema

Revision ID: fa697ddee3ca
Revises: 
Create Date: 2026-09-15 04:25:29.556008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa697ddee3ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('country_default', sa.CHAR(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_guests_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests')),
    sa.UniqueConstraint('organization_id', 'phone_e164', name=op.f('uq_guests_organization_id_phone_e164'))
    )
    op.create_index(op.f('ix_guests_organization_id'), 'guests', ['organization_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('country', sa.CHAR(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('whatsapp_business_number', sa.String(length=32), nullable=True),
    sa.Column('default_notification_channel', sa.Enum('WHATSAPP', 'SMS', name='notificationchannel', length=20), nullable=False),
    sa.Column('no_show_timeout_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('frequent_guest_threshold', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_locations_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_locations_organization_id_slug'))
    )
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_table('location_daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('joined_count', sa.Integer(), nullable=False),
    sa.Column('seated_count', sa.Integer(), nullable=False),
    sa.Column('left_without_seating_count', sa.Integer(), nullable=False),
    sa.Column('no_show_count', sa.Integer(), nullable=False),
    sa.Column('average_wait_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('email_status', sa.Enum('PENDING', 'SENT', 'FAILED', name='emailstatus', length=20), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_recipients', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_location_daily_reports_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_location_daily_reports_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_daily_reports')),
    sa.UniqueConstraint('location_id', 'report_date', name=op.f('uq_location_daily_reports_location_id_report_date'))
    )
    op.create_index(op.f('ix_location_daily_reports_location_id'), 'location_daily_reports', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_daily_reports_organization_id'), 'location_daily_reports', ['organization_id'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('guest_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('phone_snapshot', sa.String(length=20), nullable=False),
    sa.Column('party_size', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'CALLED', 'SEATED', 'CANCELLED', 'NO_SHOW', name='waitliststatus', length=20), nullable=False),
    sa.Column('sort_order', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('seated_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('no_show_at', sa.DateTime(), nullable=True),
    sa.Column('guest_response', sa.Enum('ON_THE_WAY', 'NOT_COMING', name='guestresponse', length=20), nullable=True),
    sa.Column('estimated_wait_minutes_at_join', sa.SmallInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('party_size > 0', name=op.f('ck_waitlist_entries_party_size_positive')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_waitlist_entries_guest_id_guests')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_waitlist_entries_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_waitlist_entries_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waitlist_entries')),
    sa.UniqueConstraint('public_token', name=op.f('uq_waitlist_entries_public_token'))
    )
    op.create_index(op.f('ix_waitlist_entries_joined_at'), 'waitlist_entries', ['joined_at'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_location_id'), 'waitlist_entries', ['location_id'], unique=False)
    op.create_index('ix_waitlist_entries_location_status_sort', 'waitlist_entries', ['location_id', 'status', 'sort_order'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_organization_id'), 'waitlist_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_sort_order'), 'waitlist_entries', ['sort_order'], unique=False)
    op.create_table('notification_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waitlist_entry_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'SMS', name='notificationchannel', length=20), nullable=False),
    sa.Column('purpose', sa.Enum('TABLE_READY', name='notificationpurpose', length=30), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('template_external_id', sa.String(length=150), nullable=True),
    sa.Column('country', sa.CHAR(length=2), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('recipient_phone_e164', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_message_id', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'FAILED', 'REJECTED', name='notificationstatus', length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_currency', sa.CHAR(length=3), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('guest_response_action', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['waitlist_entry_id'], ['waitlist_entries.id'], name=op.f('fk_notification_attempts_waitlist_entry_id_waitlist_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_attempts'))
    )
    op.create_index(op.f('ix_notification_attempts_waitlist_entry_id'), 'notification_attempts', ['waitlist_entry_id'], unique=False)
    op.create_table('waitlist_event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waitlist_entry_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_waitlist_event_log_location_id_locations')),
    sa.ForeignKeyConstraint(['waitlist_entry_id'], ['waitlist_entries.id'], name=op.f('fk_waitlist_event_log_waitlist_entry_id_waitlist_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waitlist_event_log'))
    )
    op.create_index(op.f('ix_waitlist_event_log_location_id'), 'waitlist_event_log', ['location_id'], unique=False)
    op.create_index(op.f('ix_waitlist_event_log_occurred_at'), 'waitlist_event_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_waitlist_event_log_waitlist_entry_id'), 'waitlist_event_log', ['waitlist_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_event_log_waitlist_entry_id'), table_name='waitlist_event_log')
    op.drop_index(op.f('ix_waitlist_event_log_occurred_at'), table_name='waitlist_event_log')
    op.drop_index(op.f('ix_waitlist_event_log_location_id'), table_name='waitlist_event_log')
    op.drop_table('waitlist_event_log')
    op.drop_index(op.f('ix_notification_attempts_waitlist_entry_id'), table_name='notification_attempts')
    op.drop_table('notification_attempts')
    op.drop_index(op.f('ix_waitlist_entries_sort_order'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_organization_id'), table_name='waitlist_entries')
    op.drop_index('ix_waitlist_entries_location_status_sort', table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_location_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_joined_at'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index(op.f('ix_location_daily_reports_organization_id'), table_name='location_daily_reports')
    op.drop_index(op.f('ix_location_daily_reports_location_id'), table_name='location_daily_reports')
    op.drop_table('location_daily_reports')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_guests_organization_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_table('organizations')
    # ### end Alembic commands ###
