"""location slug globally unique

Revision ID: 2a9af2589441
Revises: fa697ddee3ca
Create Date: 2026-09-15 04:49:48.222132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9af2589441'
down_revision: Union[str, None] = 'fa697ddee3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_locations_organization_id_slug', table_name='locations')
    op.create_unique_constraint(op.f('uq_locations_slug'), 'locations', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_locations_slug'), 'locations', type_='unique')
    op.create_index('uq_locations_organization_id_slug', 'locations', ['organization_id', 'slug'], unique=True)
    # ### end Alembic commands ###
