"""widen waitlist_entries sort_order precision

Revision ID: 428f52db98f1
Revises: 2a9af2589441
Create Date: 2026-09-15 04:50:57.995976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '428f52db98f1'
down_revision: Union[str, None] = '2a9af2589441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitlist_entries', 'sort_order',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               type_=sa.Numeric(precision=30, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitlist_entries', 'sort_order',
               existing_type=sa.Numeric(precision=30, scale=10),
               type_=mysql.DECIMAL(precision=20, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###
